server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    resolver kube-dns.kube-system.svc.cluster.local valid=10s;

    location /api/ {
        set $backend_url http://backend.default.svc.cluster.local:8080;
        proxy_pass $backend_url;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
