server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://backend-281028312447.asia-east1.run.app;
        proxy_set_header Host backend-281028312447.asia-east1.run.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Origin "";
        proxy_ssl_verify off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
